[versions]
# plugin
kotlin = "2.2.21"
shadow = "9.2.2"

# library
kotlinxSerizliationJson = "1.9.0"
ktor = "3.0.3"
slf4j = "2.0.9"
kaml = "0.70.0"
lavaplayer = "2.2.4"
jda = "6.1.2"
jdave = "0.1.5"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
kotlinxSerizliationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerizliationJson"}
ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktorClientCIO = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
jdave-api = { module = "club.minnced:jdave-api", version.ref = "jdave" }
jdave-linux-x86 = { module = "club.minnced:jdave-native-linux-x86-64", version.ref = "jdave" }
jdave-linux-aarch64 = { module = "club.minnced:jdave-native-linux-aarch64", version.ref = "jdave" }
jdave-win-x86 = { module = "club.minnced:jdave-native-win-x86-64", version.ref = "jdave" }
jdave-darwin = { module = "club.minnced:jdave-native-darwin", version.ref = "jdave" }

[bundles]
ktor = [
    "ktorClientCore",
    "ktorClientCIO"
]

jdave = [
    "jdave-api",
    "jdave-linux-x86",
    "jdave-linux-aarch64",
    "jdave-win-x86",
    "jdave-darwin"
]
